envname=santana
version=nightly
cluster=santana
helper_image=centos7k
helper_sleep=15
image=rhcos44
api_ip=10.19.115.248
public_api_ip=
bootstrap_api_ip=
domain=karmalabs.com
network="VM Network"
masters=1
workers=2
tag=cnvlab
pub_key=~/.ssh/id_rsa.pub
pull_secret=openshift_pull.json
upstream=False
force=False

